### PR TITLE
Upload artifact and create release on master

### PR DESCRIPTION
**Pull request by Wissididom**
I just made a new workflow that creates a nightly release with prebuilt binaries, because that would reduce the time in another workflow that is currently using `cargo install --git https://github.com/kevinastone/httpbox --rev 89b971f` and therefore recompiles it every time the workflow is run. It would be nice to be able to use prebuilt binaries, so I thought I just do a new GitHub Actions workflow for your repo that does that. If you want to make a Release outside of the Nightly build, you should be able to just download the artifacts that workflow produces and upload them to a release.

I tried to stay close to the rust.yml file or rather took that as a template, I'm not sure if I should remove the Test step from the jobs in release.yml tho.

### CODE REVIEW

**Comment by kevinastone** [comment]
Could you expand on the use-case here?  Where are these pre-built executables being consumed?

1. There's some specific questions about the value of building pre-complied releases on multiple rust versions.  I would guess we'd just build on a single rust target (`stable`).

2. Triggering of this workflow seems inconsistent.  What would the benefit of running this on `master`, `pull-request` and `workflow_dispatch` (presumably for manual trigger)?

3. There's some unnecessary test running for a release workflow.

I'm not sure this belongs in this repo.  If you have a workflow that depends and builds this binary, wouldn't caching in that workflow better support this case?

**Comment by Wissididom** [comment]
My Use-Case would be this: https://github.com/Wissididom/chatterino2/pull/24

1. That's just because I used the rust.yml as base.
2. The benefit of running it on master would be that create-release part that automatically creates a nightly-build tag and a corresponding release and updates it on every push to master (`if: github.ref == 'refs/heads/master'`). The workflow_dispatch is for manual triggering, yes. and for the pull-request I think it is self explanatory where it runs.
3. For the tests, you're right I overlooked removing that.

I need to look into caching and how that might work because I never used caching myself. I just thought of prebuilt binaries because we just need it as a background service that responds to calls from `ctest`, which is the same we did for another go binary that used to be run inside a docker container.

**Review by Nerixyz — COMMENTED** [review]
It would be cool if this was compatible with [cargo-binstall](https://github.com/cargo-bins/cargo-binstall). I think [cargo-dist](https://github.com/axodotdev/cargo-dist) might be easier to use for releases than a manual script (as you just need to push a tag, and it does the release for you). If the docs are correct, then [cargo-binstall should just work](https://github.com/axodotdev/cargo-dist/blob/6c5ab508d3a1506f77e2b93d9b73b5fccabe97cc/book/src/installers/other.md).

**Comment by Nerixyz** [comment]
@kevinastone Could you look at the changes now? I've switched from a custom release pipeline to [cargo dist](https://opensource.axo.dev/cargo-dist/). The only thing I've done is that I ran `cargo dist init`. There have been a few more releases since I made the change, but you update CI by running `cargo dist init` again (it will ask you to update, and you should be able to push on this branch).

To make a release, you just have to tag a commit and push that tag (as explained on the website).

**Comment by kevinastone** [comment]
Thanks for this and sorry for the delay.  Let's give it a go!

**Comment by Nerixyz** [comment]
@kevinastone you'd still need to `git tag` a version which would then be released as [described on the website](https://opensource.axo.dev/cargo-dist/):

```shell
git tag "v0.2.1"
git push
git push --tags
```

In that case, the version should probably be changed in Cargo.toml too and published to crates.io. https://github.com/crate-ci/cargo-release is a tool I found useful which automatically bumps the version, tests, runs `cargo publish`, and pushes a commit & tags - by running `cargo release patch/minor/major`.

**Pull request merged**
